---
# control
control:
  data_name: CIFAR10
  model_name: resnet18
  prune_iters: 10
  prune_scope: layer
  prune_mode: si-0.5-1-0-1 # p-q-eta_r-gamma
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
